name: Build


on: workflow_dispatch

jobs:
  applet_tests:
    runs-on: ubuntu-20.04
    steps:

      - name: checkout repository
        uses: actions/checkout@v2

      - name: applet tests
        shell: bash
        run: |
          # get dependencies
          echo "==== get dependencies";
          sudo apt-get install -y --no-install-recommends procps autoconf automake libtool m4 pkg-config help2man make gcc ant automake autotools-dev sudo wget gnupg software-properties-common maven git pcscd libpcsclite-dev opensc;
          sudo apt-get install -y python3-setuptools python3-pyscard python3-pyasn1;
          pip3 install OpenPGPpy;
          # get JavaCard SDKs
          echo "==== get JavaCard SDKs";
          git clone https://github.com/martinpaljak/oracle_javacard_sdks && mv oracle_javacard_sdks/jc304_kit/ /tmp/ && mv oracle_javacard_sdks/jc305u4_kit/ /tmp/ && rm -rf oracle_javacard_sdks;
          # compile SmartPGP
          echo "==== compile SmartPGP";
          cat build.xml | sed 's/<cap /<cap export="SmartPGPApplet" /' > /tmp/build.xml && mv /tmp/build.xml ./;
          JC_HOME=/tmp/jc304_kit/ ant;
      - uses: actions/upload-artifact@v4
        with:
          path: ./
